import {useEffect,useMemo,useState} from 'react';import {HistoryMap} from '../features/map/HistoryMap';import {Timeline} from '../features/timeline/Timeline';import {createRepository} from '../data/repository';import {createHistoryController} from '../state/controller';import {useHistory} from '../state/useHistory';import {defaultQuery} from '../domain/query';import type {Catalog,SearchEntry,Query} from '../domain/types';
const emptyCatalog:Catalog={sources:[],entities:[],places:[]};
export default function App(){const repository=useMemo(()=>createRepository(),[]),controller=useMemo(()=>createHistoryController(repository),[repository]),state=useHistory(controller);const [catalog,setCatalog]=useState(emptyCatalog),[index,setIndex]=useState<SearchEntry[]>([]),[mapUnavailable,setMapUnavailable]=useState('');
 useEffect(()=>{const abort=new AbortController();repository.overview(abort.signal).then(o=>{setCatalog(o.catalog);setIndex(o.index)}).catch(()=>{});void controller.request(defaultQuery());return ()=>{abort.abort();controller.dispose()}},[controller,repository]);
 useEffect(()=>{if(mapUnavailable&&state.pending)controller.acceptRendered(state.pending.requestId)},[mapUnavailable,state.pending,controller]);
 const scene=state.committed;const request=(q:Query)=>{void controller.request(q)};
 return <div className="app"><header className="masthead"><div className="brand"><span className="brand-seal" aria-hidden="true">舆</span><h1>山河纪</h1></div><span className="masthead-subtitle">三国至唐末的时间与疆域</span><span className="header-year">公元 <b data-testid="committed-year">{scene?.query.year??'—'}</b> 年</span><span className="status-tag" data-testid="scene-status">{state.status==='ready'?'已更新':state.status==='error'?'资料加载失败':'载入中'}</span></header>
 <main className="workspace"><HistoryMap scene={scene} pending={state.pending} onRendered={controller.acceptRendered} onSelect={controller.select} onUnavailable={setMapUnavailable} selected={state.selection}/>{state.error&&<div className="load-error" role="alert"><h2>资料暂时无法加载</h2><p>{state.error}</p><button onClick={()=>request(scene?.query??defaultQuery())}>重新加载</button></div>}{scene&&<div className="coverage-banner">{scene.warnings[0]??'显示已核验资料'}<span>底图为现代自然地理参考</span></div>}</main>
 <Timeline state={state} catalog={catalog} onPreview={controller.preview} onRequest={request} onPlaying={controller.setPlaying} eventYears={index.filter(i=>i.kind==='event').map(i=>i.startYear)} onEntity={id=>controller.select({kind:'entity',id})}/>
 </div>
}
